project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "content/*.qmd"
    - "content/practice/practice1.qmd"
    - "content/practice/practice2.qmd"
    - "content/practice/practice3.qmd"
    - "!content/practice/practice4.qmd"
    - "!content/practice/practice5.qmd"
    - "!content/practice/practice6.qmd"
    - "!content/practice/practice7.qmd"
    - "content/slides/slides1.qmd"
    - "content/slides/slides2.qmd"
    - "content/slides/slides3.qmd"
    - "!content/slides/slides4.qmd"
    - "!content/slides/slides5.qmd"
    - "!content/slides/slides6.qmd"
    - "!content/slides/slides7.qmd"
    - "!grades/"
    - "!lectures-old/"
    - "!project/"
    - "!exams.qmd"

execute:
  freeze: auto


website:
  title: "Introduction to Mathematical Economics"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus.qmd
      - text: "Schedule"
        file: schedule.qmd
      - text: "Content"
        file: content/preliminaries.qmd
      - icon: github
        href: https://divbhagia.github.io/econ441/
        aria-label: GitHub repository for this course

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      contents:
        - text: "I. Preliminaries"
          file: content/preliminaries.qmd
        - text: "II. Linear Algebra"
          file: content/linear-algebra.qmd
        - text: "III. Calculus"
          file: content/calculus.qmd
        - text: "IV. Optimization"
          file: content/optimization.qmd

  page-footer:
      2026 Div Bhagia | [CC BY-NC 4.0 License](https://creativecommons.org/licenses/by-nc/4.0/) | [Accessibility](/accessibility.qmd) | Made with [Quarto](https://quarto.org/)

format:
  html:
    theme: assets/custom.scss
    toc: true
    link-external-newwindow: true
    css: assets/styles.css
    include-after-body: assets/site-a11y.html
