---
title: "Practice Problems 3"
subtitle: "Lecture 3: Matrices and Matrix Operations"
format: html
---

Problem numbers refer to the textbook (Chiang & Wainwright, 4th edition). These are not graded, but you should attempt them all before the quiz. Try each exercise yourself first, then expand the solutions to check.

## Exercise 4.2

-   Given $A=\left[\begin{array}{cc}7 & -1 \\ 6 & 9\end{array}\right],  B=\left[\begin{array}{cc}0 & 4 \\ 3 & -2\end{array}\right], \text{ and }C=\left[\begin{array}{ll}8 & 3 \\ 6 & 1\end{array}\right]$, find:

    1.  $A+B$

    2.  $C-A$

    3.  $3A$

    4.  $4B+2C$

-   Given $A = \left[\begin{array}{cc}
    2 & 8 \\
    3 & 0 \\
    5 & 1
    \end{array}\right], B=\left[\begin{array}{cc} 2 & 0 \\ 3 & 8\end{array}\right], \text{ and }
    C=\left[\begin{array}{cc} 7 & 2 \\ 6 & 3\end{array}\right]$:

    1.  Is $AB$ defined? Calculate $AB$. Can you calculate $BA$? Why?

    2.  Is $BC$ defined? Calculate $BC$. Is $CB$ defined? If so, calculate $CB$. Is it true that $BC=CB$.

-   Find the product matrices in the following (in each case, append beneath every matrix a dimension indicator):

    1.  $\left[\begin{array}{lll}0 & 2 & 0 \\ 3 & 0 & 4 \\ 2 & 3 & 0\end{array}\right]\left[\begin{array}{ll}8 & 0 \\ 0 & 1 \\ 3 & 5\end{array}\right]$

    2.  $\left[\begin{array}{rrr}6 & 5 & -1 \\ 1 & 0 & 4\end{array}\right]\left[\begin{array}{rr}4 & -1 \\ 5 & 2 \\ 0 & 1\end{array}\right]$

    3.  $\left[\begin{array}{rrr}3 & 5 & 0 \\ 4 & 2 & -7\end{array}\right]\left[\begin{array}{l}x \\ y \\ z\end{array}\right]$

    4.  $\left[\begin{array}{lll}a & b & c\end{array}\right]\left[\begin{array}{ll}7 & 0 \\ 0 & 2 \\ 1 & 4\end{array}\right]$

<details class="solution">
<summary>Show solutions for Exercise 4.2</summary>

1.  $A=\left[\begin{array}{cc}7 & -1 \\ 6 & 9\end{array}\right] \quad B=\left[\begin{array}{cc}0 & 4 \\ 3 & -2\end{array}\right] \quad C=\left[\begin{array}{ll}8 & 3 \\ 6 & 1\end{array}\right]$

    1.  $A+B=\left[\begin{array}{ll}7 & 3 \\ 9 & 7\end{array}\right]$

    2.  $C-A=\left[\begin{array}{cc}1 & 4 \\ 0 & -8\end{array}\right]$

    3.  $3 A=\left[\begin{array}{cc}21 & -3 \\ 18 & 27\end{array}\right]$

    4.  $4 B+2 C=\left[\begin{array}{cc}0 & 16 \\ 12 & -8\end{array}\right]+\left[\begin{array}{cc}16 & 6 \\ 12 & 2\end{array}\right]=\left[\begin{array}{cc}16 & 22 \\ 24 & -6\end{array}\right]$\
         \

2.  $A = \left[\begin{array}{cc}
    2 & 8 \\
    3 & 0 \\
    5 & 1
    \end{array}\right] \quad B=\left[\begin{array}{cc} 2 & 0 \\ 3 & 8\end{array}\right] \quad
    C=\left[\begin{array}{cc} 7 & 2 \\ 6 & 3\end{array}\right]$

    1.  $A B$ is defined as number of columns in $A$ is two which is equal to the number of rows in $B$. $$A B=\left[\begin{array}{cc}
        2 \times 2+8 \times 3 & 2 \times 0+8 \times 8 \\
        3 \times 2+0 \times 3 & 3 \times 0+0 \times 8 \\
        5 \times 2+1 \times 3 & 5 \times 0+1 \times 8
        \end{array}\right]=\left[\begin{array}{cc}
        28 & 64 \\
        6 & 0 \\
        13 & 8
        \end{array}\right]$$ Not possible to calculate BA as $B$ has two columns, but $A$ has three rows.

    2.  $B C$ and $C B$ are both defined as both have two rows and two columns. $$B C=\left[\begin{array}{ll}
        14 & 4 \\
        69 & 30
        \end{array}\right] \neq C B=\left[\begin{array}{cc}
        20 & 16 \\
        21 & 24
        \end{array}\right]$$\

3.  1.  $\left[\begin{array}{cc}0 & 2 \\ 36 & 20 \\ 16 & 3\end{array}\right]_{3 \times 2}$

    2.  $\left[\begin{array}{ll}49 & 3 \\ 4 & 3\end{array}\right]_{2 \times 2}$

    3.  $\left[\begin{array}{l}3 x+5 y \\ 4 x+2 y-7 z\end{array}\right]_{2 \times 1}$

    4.  $[7 a+c \quad 2 b+4 c]$\
         \

</details>
