---
title: "The Determinant and the Inverse"
subtitle: "ECON 441: Introduction to Mathematical Economics<br>Lecture 6"
author: "Div Bhagia"
format:
  revealjs:
    theme: [default, ../../assets/slides.scss]
    embed-resources: true
---

## Checking for Nonsingularity

Rank of a matrix $=$ maximum number of linearly independent rows or (equivalently) columns

If a square matrix has full rank, it is nonsingular.

To check for nonsingularity, calculate the *determinant*: for singular matrices, the determinant is zero.

## Determinant

Determinant $|A|$ is a unique scalar associated with a *square* matrix $A$.\
 \
Determinant of a $2 \times 2$ Matrix: $$A=\left[\begin{array}{ll}a_{11} & a_{12} \\ a_{21} & a_{22}\end{array}\right]$$ Can be calculated as: $$|A|=a_{11} a_{22}-a_{12} a_{21}$$

## Determinant of a $3 \times 3$ Matrix

$$\begin{aligned}
|A| &=\left|\begin{array}{lll}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{array}\right| \\~\\
&=a_{11}\left|\begin{array}{ll}
a_{22} & a_{23} \\
a_{32} & a_{33}
\end{array}\right|-a_{12}\left|\begin{array}{ll}
a_{21} & a_{23} \\
a_{31} & a_{33}
\end{array}\right| 
+a_{13}\left|\begin{array}{ll}
a_{21} & a_{22} \\
a_{31} & a_{32}
\end{array}\right|
\end{aligned}$$

## Determinant of a $n \times n$ Matrix

A *minor* of the element $a_{ij}$, denoted by $|M_{ij}|$ is obtained by deleting the $i$th row and $j$th column.\
 \
Cofactor $C_{ij}$ is defined as: $$|C_{ij}| = (-1)^{i+j} |M_{ij}|$$ Then, $$|A| = \sum_{i=1}^n a_{ij} |C_{ij}| = \sum_{j=1}^n a_{ij} |C_{ij}|$$

## Find the Determinant

$$A=\left[\begin{array}{ccc}
1 & 5 & 1 \\
0 & 3 & 9 \\
-1 & 0 & 0
\end{array}\right]$$

## Properties of Determinants

$|A| = |A^T|$

Interchanging rows or columns will alter the sign but not the value

Multiplication of any one row (or one column) by a scalar $k$ will change the value of the determinant $k$-fold

The addition (subtraction) of a multiple of any row (or column) to (from) another row (or column) will leave the determinant unaltered

If one row (or column) is a multiple of another row (or column), the value of the determinant will be zero.

## Criteria for Nonsingularity

The following statements are equivalent:


$|A| \neq 0$

Rows (or equivalently columns) of $A$ are independent

$A$ has full rank

$A$ is nonsingular

$A^{-1}$ exists

A unique solution to $A x=b$ ($x^*=A^{-1}b$) exists

## Matrix Inversion

*Adjoint* of a nonsingular $n \times n$ matrix\
 \
$$adj A = C^T = \left[\begin{array}{llll}
|C_{11}| & |C_{21}| & \cdots & |C_{n1}| \\
|C_{12}| & |C_{22}| & \cdots &  |C_{n2}| \\
\vdots &\vdots & \cdots &  \vdots \\
|C_{1n}| & |C_{2n}| & \cdots & |C_{nn}| \\
\end{array}\right]$$ $$A^{-1} = \frac{1}{|A|} Adj A$$

## Find the Inverse

$$A=\left[\begin{array}{ccc}
3 & 2 \\
1 & 0 \\
\end{array}\right]$$

## Find the Inverse

$$A=\left[\begin{array}{ccc}
1 & 5 & 1 \\
0 & 3 & 9 \\
-1 & 0 & 0
\end{array}\right]$$

## Homework Questions

-   Exercise 5.2: 1 (c), (e), (f), 2, 3, 6

-   Exercise 5.3: 1, 4, 5, 8

-   Exercise 5.4: 2, 3, 4, 7

Textbook reference: 5.2-5.4
