---
title: "Identity, Null, and Transpose Matrices"
subtitle: "ECON 441: Introduction to Mathematical Economics<br>Lecture 5"
author: "Div Bhagia"
format:
  revealjs:
    theme: [default, ../../assets/slides.scss]
    embed-resources: true
---

## Identity Matrices

Square matrix with $1$s in its *principal diagonal* and $0$s elsewhere\
 \
A $2 \times 2$ identity matrix: $$I_2 = \begin{bmatrix}
1 & 0\\
0 & 1 \\
\end{bmatrix}$$ A $3 \times 3$ identity matrix: $$I_3 = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}$$

## Identity Matrices

Acts like 1, $$AI = IA = A$$

Example. $$A = \begin{bmatrix}
2 & 3 & 1 \\
4 & -6 & 2
\end{bmatrix}$$

## Idempotent Matrices

A matrix is an *idempotent* matrix if it remains unchanged when multiplied by itself any number of times.\
 \
$A$ is idempotent if and only if $A = A^k$.\
 \
Is an identity matrix idempotent?

## Null Matrix

A null matrix is a matrix with all elements $0$.\
 \
$$\begin{bmatrix}
0 & 0 & 0 \\
0 & 0 & 0
\end{bmatrix}$$


$A + 0 = A$

$A 0 = 0$

## Transpose of a Matrix

Transpose of A ($A'$ or $A^T$): interchange rows and columns\
 \
$$A = \begin{bmatrix}
2 & 3 & 1 \\
4 & -6 & 2
\end{bmatrix}$$

## Transpose of a Matrix

A matrix $A$ is said to be *symmetric* if $$A'=A$$

A matrix $A$ is said to be *skew-symmetric* if $$A'=-A$$

A matrix $A$ is said to be *orthogonal* if $$A'A=I$$

## Example: Symmetric Matrix

$$A=\left[\begin{array}{rrr}
1 & 2 & 0 \\
2 & 3 & -5 \\
0 & -5 & 4
\end{array}\right]$$

## Example: Skew-symmetric Matrix

$$A=\left[\begin{array}{ccc}0 & -1 & 3 \\ 1 & 0 & -4 \\ -3 & 4 & 0\end{array}\right]$$

## Example: Orthogonal Matrix

$$A=\left[\begin{array}{cc}
\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}}
\end{array}\right]$$

## Properties of Transposes

$$\begin{array}{l}
\left(A^{\prime}\right)^{\prime}=A \\~\\
(A+B)^{\prime}=A^{\prime}+B^{\prime} \\~\\
(A B)^{\prime}=B^{\prime} A^{\prime} \\~\\
\end{array}$$ Example: $A=\left[\begin{array}{ll}4 & 1 \\ 9 & 0\end{array}\right] \quad B=\left[\begin{array}{ll}2 & 0 \\ 7 & 1\end{array}\right]$
