---
title: 'ECON 441'
subtitle: 'Lecture 1: Preliminaries'
author: 'Div Bhagia'
format: revealjs
---

### Today's Topics & References
-   Numbers and sets (sections 2.2 and 2.3)
-   Relations and functions (sections 2.4-2.6, page 163)
-   Summation notation (handout)
-   Necessary and sufficient conditions (beginning of 5.1)

# Numbers and Sets

::: frame
### Real-Number System

-   *Integers*: $$...,-3,-2,-1,0,1,2,3,...$$

-   *Fractions*: $$\frac{1}{2}, \frac{3}{5}, -\frac{2}{3}$$

-   *Rational numbers*: ratio of integers

-   *Are fractions rational numbers? What about integers?*
:::

::: frame
### Real-Number System

-   *Rational numbers*: ratio of integers

-   "terminating or repeating decimal"

-   $$\text{Example. } \frac{1}{3}=0.333, \frac{1}{4}=0.25$$

-   *Irrational numbers:* cannot be expressed as a ratio of two integers

-   "nonterminating or nonrepeating decimal"

-   $$\text{Example. } \sqrt{2}=1.4142, \pi=3.1415$$

-   *Real numbers ($\mathbb{R}$): rational and irrational*
:::

::: frame
### Sets

-   A *set* is a collection of distinct objects.
    $$A = \{brownies, icecream, pizza, ramen\}$$

-   $pizza \in A$, $\in$ stands for 'is in'

-   What about sets $B$ and $C$?
    $$B = \{x | x \text{ is a positive integer}\}$$
    $$C = \{x | 1<x<5\}$$
:::

::: frame
### Set Relations

-   Equivalence ($=$) $$A = \{brownies, icecream, pizza, ramen\}$$
    $$B = \{pizza, ramen, icecream, brownies\}$$ $$A = B$$

-   Subset ($\subset$) $$C = \{pizza, ramen\}$$ $C \neq A$ but
    $C \subset A$. Note: $A \supset C$ is equivalent. *Is $A \subset B$?
    Yes, but $C$ is a proper subset of A.*
:::

::: frame
### Set Relations

-   Disjoint sets $$A = \{brownies, icecream, pizza, ramen\}$$
    $$D = \{salad, fruits\}$$

-   Neither but still related
    $$A = \{brownies, icecream, pizza, ramen\}$$
    $$E = \{salad, fruits, icecream\}$$
:::

::: frame
### Set Relations

-   $\emptyset$: empty or null set

-   What are all possible subsets of $$S = \{a,b,c\}$$

-   $\emptyset, \{a\}, \{b\},\{c\}, \{a,b\}, \{b,c\}, \{a,c\}, \{a,b,c\}$
    Always $2^n$ subsets. Here $n=3$, so 8 subsets.
:::

::: frame
### Set Operations

-   *Union:* $A \cup B$, elements in either $A$ *or* $B$

-   *Intersection:* $A \cap B$, elements in both $A$ *and* $B$

Example: $$A = \{brownies, icecream, pizza, ramen\}$$
$$B = \{salad, fruits, icecream\}$$ $A \cup B =$ $A \cap B =$
:::

::: frame
### Set Operations

-   *Union:* $A \cup B$, elements in either $A$ or $B$

-   *Intersection:* $A \cap B$, elements in both $A$ and $B$

What about $$A = \{brownies, icecream, pizza, ramen\}$$
$$B = \{salad, fruits\}$$ $A \cup B =$ $A \cap B =$
:::

::: frame
### Set Operations

-   *Complement of $A$*: $\tilde{A}$, 'not $A$'

-   Universal set $U$ (context specific) then:
    $$\tilde{A}= \{x | x \in U \text{ and } x \not\in A\}$$ Example.
    $U=\{1,e,f,2\}, A=\{1,2\}$, then $\tilde{A}=\{e,f\}$.
:::

::: frame
### Set Operations: Venn Diagrams

::: venndiagram2sets
:::

::: venndiagram2sets
:::

::: venndiagram2sets
:::
:::

::: frame
### Laws of Set Operations

-   Commutative law
    $$A \cup B = B \cup A \quad \quad  A \cap B = B \cap A$$

-   Distributive law $$A \cup (B \cap C) = (A \cup B) \cap (A \cup C)$$
    $$A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$$
:::

::: frame
### Distributive law

$= (A \cup B) \cap (A \cup C)$

::: columns
::: column
0.5 $A$

::: venndiagram3sets
:::
:::

::: column
0.5 $B \cap C$

::: venndiagram3sets
:::
:::
:::
:::

::: frame
### Distributive law

$A \cup (B \cap C)=$

::: columns
::: column
0.5 $A \cup B$

::: venndiagram3sets
:::
:::

::: column
0.5 $A \cup C$

::: venndiagram3sets
:::
:::
:::
:::

::: frame
### Ordered Sets

-   We said order does not matter for sets

-   But we can have ordered sets where
    $$(a,b) \neq (b,a) \text{ unless } a=b$$

-   Ordered pairs, triples,\...

Example. $(age, weight)$, $(22,120)$ different from $(120,22)$
:::

::: frame
### Cartesian Product

$$A = \{1,2\} \quad B = \{3,4\}$$ Cartesian Product: set of all possible
ordered pairs $$A \times B = \{ (1,3), (1,4), (2,3), (2,4) \}$$
:::

::: frame
### Cartesian Plane

$$\mathbb{R}^2 =  \{(x,y) | x \in \mathbb{R}, y \in \mathbb{R}\}$$

Can have $\mathbb{R}^3, \mathbb{R}^4,...,\mathbb{R}^n$
:::

# Relations and Functions

::: frame
### Relations

Relation: subset of the Cartesian product Example.
$\{(x,y) | y \leq x \}$
:::

::: frame
### Functions

Function: a relation where for each $x$ there is a unique $y$
$$f: X \rightarrow Y, \quad y = f(x)$$ Examples. $y = x, y=x^2, y=2x+3$

$X:$ domain, $Y:$ codomain, $f(X):$ range

Most functions we will encounter,
$f: \mathbb{R}^k \rightarrow \mathbb{R}$
:::

::: frame
### Functions

Let's say, $$f: X \rightarrow \mathbb{R}, \quad y = 3x-5$$ where
$X = \{2,3,4\}$. What is the range?
:::

::: frame
### Cost Function

Consider the total cost $C$ of producing hats $Q$, $$C = f(Q)$$

-   Should I be able to produce 10 hats and 5 hats at the same cost?

-   Possible to produce 5 hats for \$20 and \$25?
:::

::: frame
### By the way

Consider the total cost $C$ of producing hats $Q$, $$C = f(Q) = 2Q + 5$$

What is the cost of producing 1 hat? What is the cost of producing 2
hats? How many hats can I produce for \$25?
:::

::: frame
### Types of Functions

-   Constant: $y = f(x) = 5$

-   Polynomial of degree $n$

    -   $n=0$, constant

    -   $n=1$, linear

    -   $n=2$, quadratic

    -   $n=3$, cubic

    -   \...

-   Rational function: ratio of two polynomial functions:
    $$y = \frac{a}{x}$$
:::

::: frame
### Function of More than One Variables

Functions can be of two variables: $$z=g(x,y)$$ Or three, or four,\...,
or $n$
:::

::: frame
### Monotonic functions

Strictly increasing function:
$$x_{1}>x_{2} \rightarrow f\left(x_{1}\right)>f\left(x_{2}\right)$$
Strictly decreasing function:
$$x_{1}>x_{2} \rightarrow f\left(x_{1}\right)<f\left(x_{2}\right)$$
Increasing function:
$$x_{1}>x_{2} \rightarrow f\left(x_{1}\right)\geq f\left(x_{2}\right)$$
Decreasing function:
$$x_{1}>x_{2} \rightarrow f\left(x_{1}\right)\leq f\left(x_{2}\right)$$
:::

::: frame
### Inverse of a function

Function $y=f(X)$ has an inverse if it is a one-to-one mapping, i.e.
each value of $y$ is associated with a unique value of $x$. Inverse
function $$x=f^{-1}(y)$$ returns the value corresponding value of $x$
for each $y$. One-to-one mapping unique to strictly monotonic functions
:::

::: frame
### Inverse of a function

Example: Find the inverse of $y = f(x) = 3x-2$.
:::

::: frame
### By the way

What is $x \times x$? What is $x^2 \times x$? What is $x^2 \times x^2$?
More generally, $x^n \times x^m = x^{m+n}$
:::

# Summation Notation

::: frame
Summation Notation

$$\sum_{i=1}^N x_i = x_1 + x_2 + ... + x_N$$

[*Example:*]{.underline} $x = \{2,9,6,8,11,14\}$
$\sum_{i=1}^{4} x_i = x_1 + x_2 + x_3 + x_4 = 2+9+6+8=25$
:::

::: frame
### Summation Notation

Another way of using a summation sign is to write $$\sum_{x \in A} x$$
which refers to summing up all elements in $A$. To sum up $x$ for all
possible values $x$, we can simply write $$\sum_x x$$
:::

::: frame
### Things you CAN do

1.  Pull constants out of or into the summation sign.
    $$\sum_{i=1}^N b x_i = b \sum_{i=1}^N x_i$$
:::

::: frame
### Things you CAN do

1.  Split apart (or combine) sums (addition) or differences
    (subtraction)
    $$\sum_{i=1}^N (b x_i + c y_i) = b \sum_{i=1}^N x_i  + c \sum_{i=1}^N y_i$$
:::

::: frame
### Things you CAN do

1.  Multiply through constants by the number of terms in the summation
    $$\sum_{i=1}^N (a+b x_i)= aN + b \sum_{i=1}^N x_i$$
:::

::: frame
### Things you CANNOT do

1.  Split apart (or combine) products (multiplication) or quotients
    (division).
    $$\sum_{i=1}^N x_i y_i \neq  \sum_{i=1}^N x_i \times \sum_{i=1}^N y_i$$
:::

::: frame
### Things you CANNOT do

1.  Move the exponent out of or into the summation.
    $$\sum_{i=1}^N x_i^a \neq  \left(\sum_{i=1}^N x_i\right)^a$$
:::

# Necessary and Sufficient Conditions

::: frame
### Necessary vs. Sufficient Conditions

$q$ is a necessary condition for $p$ if: $$p \implies q$$

$p$: I ate tofu for dinner $q$: My dinner had protein
:::

::: frame
### Necessary vs. Sufficient Conditions

$q$ is a sufficient condition for $p$ if: $$p \impliedby q$$

$p$: A number is even $q$: A number is divisible by 4
:::

::: frame
### Necessary vs. Sufficient Conditions

$q$ is both necessary and sufficient for $p$ $$p \iff q$$

$p$: A number is even $q$: A number is divisible by 2
:::

::: frame
### Necessary vs. Sufficient Conditions

$p$: It is a holiday $q$: It is Thanksgiving
:::

::: frame
### Necessary vs. Sufficient Conditions

$p$: The car is out of gas $q$: The car isn't starting
:::

::: frame
### Necessary vs. Sufficient Conditions

$p$: A geometric figure has four sides $q$: It is a rectangle
:::

::: frame
### Homework Questions

-   Exercise 2.3: 1, 2

-   Exercise 2.4: 5, 7, 8

-   Exercise 2.5: 1 (For each part, find the inverse of the function
    too.)

-   Exercise 4.2: 6, 8

-   Exercise 5.1: 1
:::
